### ISSUE TITLE
Not compatible with the version of your running IDE (WebStorm 2024.2 EAP)

### ISSUE THREAD

**Issue by TomBrown114514** [0x3C50/easy-code-screenshots#12]
I want to use the plugins to get the screen shoot of the codes I wrote, but I installed WebStorm 2024.2 EAP, and it can't be used for this version. When will update for JetBrains 2024.2 and 2024.2 EAP?

**Comment by 0x3C50** [comment]
I generally dont go through the hustle to support EAP versions, support will come for 2024.2 when it releases to stable.
