### ISSUE TITLE
Async image generation

### ISSUE THREAD

**Issue by ghost** [0x3C50/easy-code-screenshots#3]
Right now the code to generate the image is blocking so it freezes the ide

**Comment by 0x3C50** [comment]
Could be useful, but the screenshot takes like a second, so not much time is lost. Also, the screenshotter renders the segment of code from the editor directly, multithreading might break something, but I'll try

**Comment by 0x3C50** [comment]
I took a look and tried it, intellij screamed in agony because of off thread rendering. Async screenshotting will not work with how I'm doing it right now

**Comment by ghost** [comment]
Ok no problem
