### ISSUE TITLE
Adjustable "border" color (e.g. set it to "transparent")

### ISSUE THREAD

**Issue by topnik-code** [0x3C50/easy-code-screenshots#4]
Wonderful tool, thank you so much! 💜

One thing that would make it even better:

- Adjustable "border" color (the color that appears when "Outer padding" is greater than 0).
- Specifically, it would be great if one could this to "transparent"

This would make it so much easier to use the screenshot as part of a bigger diagram. 🙂

**Comment by 0x3C50** [comment]
Working on this right now, thanks for the suggestion!

**Comment by 0x3C50** [comment]
Done! I've also uploaded a new version to the JetBrains marketplace, although that might take a few days to become available publicly, it still needs to be checked.

**Comment by topnik-code** [comment]
Wow, so fast! 😮 Thank you so much for your effort! 🙏
