### ISSUE TITLE
Background Color: Alpha value is always reset to 100%

### ISSUE THREAD

**Issue by topnik-code** [0x3C50/easy-code-screenshots#5]
The selection for the background color works in principal! 🙂👍

However, the alpha value is not taken into consideration. In fact, no matter what I choose, it seems to always reset back to 100% by itself once I re-open the settings. 😮

**Comment by 0x3C50** [comment]
Oh yeah, seems like I forgot to parse the alpha component from the saved color.

Seems to work again, I've uploaded the small fix to the marketplace again. As always, it'll take a few days for that to show publicly. Until then, you need to install the plugin from the jarfile.
