### ISSUE TITLE
Global configuration

### ISSUE THREAD

**Issue by Zarpyk** [0x3C50/easy-code-screenshots#7]
Hello, is there a way to make the configuration global instead of per project? 
It's a bit annoying having to configure it every time when using it on different project.

**Comment by 0x3C50** [comment]
I've tried to get that working a few times by now, but since I don't have much experience with idea plugins, I couldn't figure out how that works. I'll look into global configuration a bit more, maybe I'll find something

**Comment by 0x3C50** [comment]
Version 1.4.3 is now publicly available on the jetbrains marketplace
